# Generated by Django 2.2b1 on 2019-06-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finesse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_member',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='./finesse/cm'),
        ),
        migrations.AlterField(
            model_name='club_member',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='./finesse/cm'),
        ),
        migrations.AlterField(
            model_name='club_member',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='./finesse/cm'),
        ),
        migrations.AlterField(
            model_name='club_sec',
            name='image',
            field=models.FileField(upload_to='./finesse/cs'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='./finesse/gallery'),
        ),
    ]
