# Generated by Django 2.2b1 on 2019-06-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finesse', '0003_auto_20190612_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_member',
            old_name='image',
            new_name='image1',
        ),
    ]
