# Generated by Django 2.2b1 on 2019-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender', models.CharField(blank=True, max_length=500, null=True)),
                ('results', models.CharField(blank=True, max_length=500, null=True)),
                ('rulebook', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
