# Generated by Django 2.2b1 on 2019-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpressions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='slug',
        ),
        migrations.AlterField(
            model_name='youtube',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
