# Generated by Django 2.2b1 on 2019-06-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpressions', '0003_auto_20190610_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='threads',
        ),
    ]
