# Generated by Django 2.2b1 on 2019-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190524_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming_events',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upcoming_events',
            name='venue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
