# Generated by Django 2.2b1 on 2019-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(upload_to='./dynamic_media/home/team'),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='image',
            field=models.FileField(upload_to='./dynamic_media/home/upcoming_events'),
        ),
    ]
