# Generated by Django 2.2b1 on 2019-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_team_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
