# Generated by Django 2.2b1 on 2019-05-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_team_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='insta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
