# Generated by Django 2.2b1 on 2019-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_team_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
