# Generated by Django 2.2b1 on 2019-05-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190526_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='insta',
            new_name='instagram',
        ),
    ]
