# Generated by Django 2.2b1 on 2019-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheivement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Club_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('name1', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook1', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram1', models.CharField(blank=True, max_length=100, null=True)),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook2', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram2', models.CharField(blank=True, max_length=100, null=True)),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook3', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club_sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('contact_us', models.CharField(max_length=100)),
                ('email_us', models.CharField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=1000)),
            ],
        ),
    ]
