# Generated by Django 2.2b1 on 2019-06-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_sec',
            old_name='contact_us',
            new_name='contact',
        ),
    ]
