# Generated by Django 2.2b1 on 2019-06-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octaves', '0002_auto_20190611_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_member',
            old_name='image1',
            new_name='image_1',
        ),
    ]
