# Generated by Django 2.2b1 on 2019-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_member',
            old_name='facebook',
            new_name='facebook1',
        ),
        migrations.RenameField(
            model_name='club_member',
            old_name='instagram',
            new_name='facebook2',
        ),
        migrations.RemoveField(
            model_name='club_member',
            name='image',
        ),
        migrations.RemoveField(
            model_name='club_member',
            name='name',
        ),
        migrations.AddField(
            model_name='club_member',
            name='facebook3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club_member',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='club_member',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='club_member',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='club_member',
            name='instagram1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club_member',
            name='instagram2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club_member',
            name='instagram3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club_member',
            name='name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club_member',
            name='name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club_member',
            name='name3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
