# Generated by Django 2.2b1 on 2019-06-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0002_auto_20190611_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_sec',
            old_name='contact_us',
            new_name='contact',
        ),
    ]
